apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: transactions-mongodb

spec:
  serviceName: transactions-mongodb
  replicas: 1

  selector:
    matchLabels:
      app: transactions-mongodb

  template:
    metadata:
      labels:
        app: transactions-mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo:7

          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongodb-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi