apiVersion: apps/v1
kind: Deployment

metadata:
  name: hive-router

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hive-router

  template:
    metadata:
      labels:
        app: hive-router

    spec:
      containers:
        - name: hive-router
          image: servitude-router
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000