scalar Date

type Query {
  listAccounts(filter: ListAccountsFilter): [AccountBase!]!
  getAccount(id: ID!): AccountBase
}

type Mutation {
  createSavingsAccount(
    name: String!
    interestRate: Float!
    balance: Float!
    lastFourDigits: String!
  ): Account!

  createCreditCardAccount(
    name: String!
    lastFourDigits: String!
    limit: Float!
    billDate: Int!
  ): Account!

  createLoanAccount(
    name: String!
    lastFourDigits: String!
    date: Date!
    emiStartDate: Date!
    totalEMIs: Int!
    emiAmount: Float!
    totalAmount: Float!
  ): Account!

  createEMIAccount(
    name: String!
    lastFourDigits: String!
    date: Date!
    emiStartDate: Date!
    totalEMIs: Int!
    emiAmount: Float!
    totalAmount: Float!
  ): Account!
}

enum AccountType {
  SAVINGS
  CREDIT_CARD
  LOAN
  EMI
}

input ListAccountsFilter {
  limit: Int
  offset: Int
}

interface AccountBase {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
}

type Account implements AccountBase @key(fields: "_id") {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
}

type SavingsAccount implements AccountBase {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
  interestRate: Float!
  balance: Float!
}

type CreditCardAccount implements AccountBase {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
  limit: Float!
  billDate: Int!
}

type LoanAccount implements AccountBase {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
  date: Date!
  emiStartDate: Date!
  totalEMIs: Int!
  emiAmount: Float!
  totalAmount: Float!
}

type EMIAccount implements AccountBase {
  _id: ID!
  name: String!
  accountType: AccountType!
  userId: ID!
  user: User
  lastFourDigits: String!
  date: Date!
  emiStartDate: Date!
  totalEMIs: Int!
  emiAmount: Float!
  totalAmount: Float!
}

extend type User @key(fields: "_id", resolvable: false) {  # 👈 resolvable: false = owned by user-service
  _id: ID! 
}

extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.3"
    import: ["@key", "@shareable", "@external"]
  )
