name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Setup SSH
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Release app
        run: |
          echo "Getting apps with tag:subgraph..."
          apps=$(pnpm nx show projects --type=app --projects tag:subgraph)
          echo "$apps"

          if [ -z "$apps" ]; then
            exit 0
          fi

          mkdir -p releases

          while IFS= read -r APP; do
            echo "Releasing $APP..."

            echo "${{vars.SERVER_HOST}} - ${{vars.SERVER_USER}} - $APP - /${{ vars.SERVER_USER }}/${{ vars.SERVER_PATH }}/"

            pnpm nx run "$APP:build:production"

            rsync -avz \
              -e "ssh -i ./ssh_key" \
              ./dist/apps/"$APP"/ \
              ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:/${{ vars.SERVER_USER }}/${{ vars.SERVER_PATH }}/
          done <<< "$apps"
