name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm


      - name: Release app
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_HOST: ${{ vars.SERVER_HOST }}
          SERVER_USER: ${{ vars.SERVER_USER }}
          APPS_PATH: ${{ vars.APPS_PATH }}
          HIVE_REGISTRY_TOKEN: ${{ secrets.HIVE_REGISTRY_TOKEN }}
          HIVE_WORKSPACE: ${{ vars.HIVE_WORKSPACE }}
          HIVE_PROJECT: ${{ vars.HIVE_PROJECT }}
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts 2>/dev/null
          
          echo "Getting apps with tag:subgraph..."
          apps=$(pnpm nx show projects --type=app --projects tag:subgraph)
          echo "$apps"

          if [ -z "$apps" ]; then
            exit 0
          fi

          mkdir -p releases

          apps=$(pnpm nx show projects --type=app --projects tag:subgraph)

          echo "Token length: ${#HIVE_REGISTRY_TOKEN}"

          ORDER="users accounts transactions"

          for APP in $ORDER; do
            if echo "$apps" | grep -qx "$APP"; then
              echo "Releasing $APP..."

              pnpm nx run "$APP:build:production"

              pnpm hive schema:check \                
                --registry.accessToken "$HIVE_REGISTRY_TOKEN" \
                --target "$HIVE_WORKSPACE/$HIVE_PROJECT/production" \
                ./apps/$APP/src/schema/$APP.graphql \
                --service $APP

              pnpm hive schema:publish \
                --registry.accessToken "$HIVE_REGISTRY_TOKEN" \
                --target "$HIVE_WORKSPACE/$HIVE_PROJECT/production" \
                --service "$APP" \
                "./apps/$APP/src/schema/$APP.graphql" \
                --github

              rsync -avz \
                -e "ssh -i ~/.ssh/id_rsa" \
                "./dist/apps/$APP/" \
                "$SERVER_USER@$SERVER_HOST:/$SERVER_USER/$APPS_PATH/$APP/"
            fi
          done
